import { Task } from 'src/schema/task'

export const tasks: Task[] = [
  {
    id: '1',
    projectId: '1',
    taskName: 'Design Webpage',
    time: new Date(),
    taskDetail:
      'Sit amet mattis vulputate enim nulla aliquet porttitor lacus. Aliquam sem fringilla ut morbi. Arcu non odio euismod lacinia at quis risus sed. Varius duis at consectetur lorem donec massa. A arcu cursus vitae congue mauris rhoncus.',
    isDone: false,
    memberIds: ['1', '2', '3'],
    files: [
      {
        uid: '1',
        name: 'image.png',
        status: 'done',
        url: 'https://source.unsplash.com/607x601/?website',
      },
      {
        uid: '2',
        name: 'image.png',
        status: 'done',
        url: 'https://source.unsplash.com/601x601/?website',
      },
      {
        uid: '3',
        name: 'image.png',
        status: 'done',
        url: 'https://source.unsplash.com/601x602/?website',
      },
      {
        uid: '4',
        name: 'image.png',
        status: 'done',
        url: 'https://source.unsplash.com/602x601/?design',
      },
      {
        uid: '5',
        name: 'image.png',
        status: 'error',
        url: '',
      },
      {
        uid: '24',
        name: 'image.png',
        status: 'done',
        url: 'https://source.unsplash.com/601x601/?computer',
      },
      {
        uid: '33',
        name: 'image.png',
        status: 'done',
        url: 'https://source.unsplash.com/601x602/?cat',
      },
      {
        uid: '42',
        name: 'image.png',
        status: 'done',
        url: 'https://source.unsplash.com/602x601/?dog',
      },
      {
        uid: '55',
        name: '',
        status: 'done',
        url: '',
      },
      {
        uid: '51',
        name: 'image.png',
        status: 'done',
        url: '',
      },
    ],
    comments: [
      {
        id: '1',
        timestamp: new Date('August 17, 2020 08:00:00'),
        userId: '1',
        image: '',
        userImg: 'https://source.unsplash.com/700x700/?people',
        userName: 'John Dee',
        message: "I'll do Login page",
        taskId: '1',
      },
      {
        id: '2',
        timestamp: new Date('August 17, 2020 08:30:00'),
        userId: '1',
        image: '',
        userImg: 'https://source.unsplash.com/700x700/?people',
        userName: 'John Dee',
        message: 'OK, lets go dude',
        taskId: '1',
      },
      {
        id: '3',
        timestamp: new Date('August 17, 2020 09:00:00'),
        userId: '2',
        image: '',
        userImg: 'https://source.unsplash.com/800x600/?people',
        userName: 'Jane Doe',
        message: 'OK, lets go dude',
        taskId: '1',
      },
    ],
  },
  {
    id: '2',
    projectId: '1',
    taskName: 'Implement code',
    time: new Date(),
    taskDetail: 'Odio ut sem nulla pharetra. Pharetra et ultrices neque ornare aenean.',
    isDone: true,
    memberIds: ['3'],
    files: [],
    comments: [
      {
        id: '1',
        timestamp: new Date('August 17, 2020 09:00:00'),
        userId: '3',
        image: '',
        userImg: 'https://source.unsplash.com/600x900/?people',
        userName: 'Joe Dee',
        message: 'OK, lets go dude',
        taskId: '2',
      },
    ],
  },
  {
    id: '3',
    projectId: '2',
    taskName: '#1',
    time: new Date(),
    taskDetail: 'Odio ut sem nulla pharetra. Pharetra et ultrices neque ornare aenean.',
    isDone: true,
    memberIds: ['3', '4'],
    files: [],
    comments: [],
  },
  {
    id: '4',
    projectId: '2',
    taskName: '#2',
    time: new Date(),
    taskDetail: 'Odio ut sem nulla pharetra. Pharetra et ultrices neque ornare aenean.',
    isDone: true,
    memberIds: ['3', '4'],
    files: [],
    comments: [],
  },
  {
    id: '5',
    projectId: '2',
    taskName: '#3',
    time: new Date(),
    taskDetail: 'Odio ut sem nulla pharetra. Pharetra et ultrices neque ornare aenean.',
    isDone: false,
    memberIds: ['3', '4'],
    files: [],
    comments: [],
  },
  {
    id: '6',
    projectId: '2',
    taskName: '#4',
    time: new Date(),
    taskDetail: 'Odio ut sem nulla pharetra. Pharetra et ultrices neque ornare aenean.',
    isDone: false,
    memberIds: ['3', '4'],
    files: [],
    comments: [],
  },
  {
    id: '7',
    projectId: '2',
    taskName: '#5',
    time: new Date(),
    taskDetail: 'Odio ut sem nulla pharetra. Pharetra et ultrices neque ornare aenean.',
    isDone: true,
    memberIds: ['3', '4'],
    files: [],
    comments: [],
  },
  {
    id: '8',
    projectId: '3',
    taskName: 'Sunflower',
    time: new Date(),
    taskDetail:
      'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    isDone: true,
    memberIds: ['6'],
    files: [],
    comments: [],
  },
  {
    id: '9',
    projectId: '4',
    taskName: 'Proin nibh nisl condimentum id venenatis a condimentum vitae.',
    time: new Date(),
    taskDetail:
      'Lobortis feugiat vivamus at augue eget. Sed faucibus turpis in eu mi bibendum. A arcu cursus vitae congue. Nec tincidunt praesent semper feugiat nibh sed pulvinar proin.',
    isDone: false,
    memberIds: ['7', '8', '9'],
    files: [],
    comments: [],
  },
  {
    id: '10',
    projectId: '6',
    taskName: 'Implement Database',
    time: new Date('2020-08-24T09:30:00'),
    taskDetail: 'Add Database to the project',
    isDone: false,
    memberIds: ['10', '11'],
    files: [
      {
        uid: '1',
        name: 'image.png',
        status: 'done',
        url:
          'https://trello-attachments.s3.amazonaws.com/5f27b2c5284a1b4df3eb4230/5f27b385aa8a2d7fbf5a4f9b/20ab1a46b6cf02ad897d392df4b069cc/0.png',
      },
    ],
    comments: [
      {
        id: '1',
        timestamp: new Date('2020-08-21T13:30:00'),
        userId: '10',
        image: '',
        userImg:
          'https://scontent.fcnx2-1.fna.fbcdn.net/v/t1.0-9/57016885_2263206347070723_8333399360800817152_o.jpg?_nc_cat=100&_nc_sid=09cbfe&_nc_eui2=AeHfShYgHhqUPYEZVBfEhyIu5MEsBOBeAF_kwSwE4F4AX1EDum5bOctfeRzMkBg1Q5SFzDfu9HQp4q2DjSzr4aje&_nc_ohc=zWRaFqnb4lMAX_6cuUl&_nc_oc=AQm-g9LWL-ljVZ8LuchMt42oWalemshyZw7KKxTGIRCwVvZJig8v0MM7iZ_kXUA50LI&_nc_ht=scontent.fcnx2-1.fna&oh=3bd95cbfa2717cef49981dfd5d45d986&oe=5F64DF99',
        userName: 'Nhow Tonnow',
        message: 'Use PostgreSQL https://www.postgresql.org/',
        taskId: '10',
      },
      {
        id: '2',
        timestamp: new Date('2020-08-21T13:31:00'),
        userId: '10',
        image: '',
        userImg: 'https://ca.slack-edge.com/T03EKL88Y-U01858A1810-7eaef9c3165e-512',
        userName: 'Nan Kullanan',
        message: 'and Nexus https://nexus.js.org/ ',
        taskId: '10',
      },
      {
        id: '3',
        timestamp: new Date('2020-08-21T13:34:00'),
        userId: '10',
        image: '',
        userImg:
          'https://scontent.fcnx2-1.fna.fbcdn.net/v/t1.0-9/57016885_2263206347070723_8333399360800817152_o.jpg?_nc_cat=100&_nc_sid=09cbfe&_nc_eui2=AeHfShYgHhqUPYEZVBfEhyIu5MEsBOBeAF_kwSwE4F4AX1EDum5bOctfeRzMkBg1Q5SFzDfu9HQp4q2DjSzr4aje&_nc_ohc=zWRaFqnb4lMAX_6cuUl&_nc_oc=AQm-g9LWL-ljVZ8LuchMt42oWalemshyZw7KKxTGIRCwVvZJig8v0MM7iZ_kXUA50LI&_nc_ht=scontent.fcnx2-1.fna&oh=3bd95cbfa2717cef49981dfd5d45d986&oe=5F64DF99',
        userName: 'Nhow Tonnow',
        message: 'OK!',
        taskId: '10',
      },
    ],
  },
  {
    id: '11',
    projectId: '6',
    taskName: 'Progress check',
    time: new Date('2020-08-24T15:30:00'),
    taskDetail: 'normally progress check',
    isDone: false,
    memberIds: ['10', '11', '14', '13', '15', '16'],
    files: [],
    comments: [
      {
        id: '1',
        timestamp: new Date('2020-08-24T09:30:00'),
        userId: '10',
        image: '',
        userImg:
          'https://scontent.fcnx2-1.fna.fbcdn.net/v/t1.0-9/57016885_2263206347070723_8333399360800817152_o.jpg?_nc_cat=100&_nc_sid=09cbfe&_nc_eui2=AeHfShYgHhqUPYEZVBfEhyIu5MEsBOBeAF_kwSwE4F4AX1EDum5bOctfeRzMkBg1Q5SFzDfu9HQp4q2DjSzr4aje&_nc_ohc=zWRaFqnb4lMAX_6cuUl&_nc_oc=AQm-g9LWL-ljVZ8LuchMt42oWalemshyZw7KKxTGIRCwVvZJig8v0MM7iZ_kXUA50LI&_nc_ht=scontent.fcnx2-1.fna&oh=3bd95cbfa2717cef49981dfd5d45d986&oe=5F64DF99',
        userName: 'Nhow Tonnow',
        message: 'I will go',
        taskId: '11',
      },
      {
        id: '2',
        timestamp: new Date('2020-08-24T09:31:00'),
        userId: '10',
        image: '',
        userImg: 'https://ca.slack-edge.com/T03EKL88Y-U01858A1810-7eaef9c3165e-512',
        userName: 'Nan Kullanan',
        message: 'Me too',
        taskId: '11',
      },
    ],
  },
]
