name: Dashboard API (dev)
on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - 'graphql/**/*'

env:
  PROJECT_ID: artisan-playground
  SERVICE_NAME: dashboard-api
  BRANCH_NAME: develop
  SA: ${{ secrets.SA_ARTISAN_PLAYGROUND }}

jobs:
  build:
    runs-on: github-action-playground
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ env.SA }}

      - name: Build
        run: |
          cd graphql
          gcloud builds submit \
          --tag gcr.io/$PROJECT_ID/$SERVICE_NAME:$BRANCH_NAME

      - name: Deploy
        run: |
          gcloud run deploy $SERVICE_NAME-dev \
          --quiet \
          --region asia-southeast1 \
          --image gcr.io/$PROJECT_ID/$SERVICE_NAME:$BRANCH_NAME \
          --platform managed \
          --allow-unauthenticated
